name: Security Monitoring
on:
  workflow_run:
    workflows: ["CodeQL"]
    types:
      - completed
  push:
    branches: [ "master" ]
concurrency:
  group: ${{ github.workflow }}-${{ github.run_id }}
  cancel-in-progress: true
permissions:
  security-events: read
  id-token: write # This is required for requesting the JWT
jobs:
  check-alerts:
    runs-on: ubuntu-latest
    outputs:
      high_alert_status: ${{ steps.check-alerts.outputs.high_alert_status }}
      low_alert_status: ${{ steps.check-alerts.outputs.low_alert_status }}
    steps:
      - name: Check for security alerts
        id: check-alerts
        uses: actions/github-script@v7
        with:
          script: |
            async function checkAlerts() {
              const owner = context.repo.owner;
              const repo = context.repo.repo;
              const alerts = await github.rest.codeScanning.listAlertsForRepo({
                owner,
                repo,
              });
              const activeAlerts = alerts.data.filter(alert => alert.state === 'open');
              const highActiveAlerts = activeAlerts.some(alert =>
                (alert.rule.security_severity_level === 'high' || alert.rule.security_severity_level === 'critical') && alert.state !== 'dismissed'
              );
              const lowActiveAlerts = activeAlerts.some(alert =>
                (alert.rule.security_severity_level === 'low' || alert.rule.security_severity_level === 'medium') && alert.state !== 'dismissed'
              );
              core.setOutput('high_alert_status', highActiveAlerts ? '1' : '0');
              core.setOutput('low_alert_status', lowActiveAlerts ? '1' : '0');
            }
            await checkAlerts();
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  put-metric-data:
    runs-on: ubuntu-latest
    needs: [check-alerts]
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::381492231164:role/GithubActionsRole-us-west-2
          aws-region: us-west-2
      - name: Put Metric Data
        run: |
          if [ "${{ needs.check-alerts.outputs.high_alert_status }}" == "1" ]; then
            aws cloudwatch put-metric-data --metric-name HighCodeScanningAlert --namespace SecurityMonitor --value 1 --unit Count --dimensions AlertType=alert;
          else
            aws cloudwatch put-metric-data --metric-name HighCodeScanningAlert --namespace SecurityMonitor --value 0 --unit Count --dimensions AlertType=alert;
          fi
          if [ "${{ needs.check-alerts.outputs.low_alert_status }}" == "1" ]; then
            aws cloudwatch put-metric-data --metric-name HighCodeScanningAlert --namespace SecurityMonitor --value 1 --unit Count --dimensions AlertType=alert;
          else
            aws cloudwatch put-metric-data --metric-name HighCodeScanningAlert --namespace SecurityMonitor --value 0 --unit Count --dimensions AlertType=alert;
          fi
